import type { Metadata } from "next";

import {
  AppProvider,
  MobileWebProvider,
  PortalProvider,
} from "@/app/core/Providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "아끼미",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css"
        />
      </head>
      <body>
        <AppProvider>
          <PortalProvider>
            <MobileWebProvider>{children}</MobileWebProvider>
          </PortalProvider>
        </AppProvider>
      </body>
    </html>
  );
}
