import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

import { MobileWebProvider } from "@/app/core/Providers";

import "./globals.css";

const notoSansKr = Noto_Sans_KR({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "아끼미",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <MobileWebProvider>{children}</MobileWebProvider>
      </body>
    </html>
  );
}
