name: git push into personal lazydoer repo to deploy to vercel

on:
  push:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "canoe918"
          git config --global user.email "canoe918@lazydoer.com"

      - name: Save current remote URL
        id: save-url
        run: echo "::set-output name=url::$(git remote get-url origin)"

      - name: Force push to develop branch
        if: github.ref == 'refs/heads/develop'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git remote set-url origin https://canoe918:${API_TOKEN_GITHUB}@github.com/canoe918/akkimi-web.git
          git push origin HEAD:develop --force
          git remote set-url origin ${{ steps.save-url.outputs.url }}
